import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <ClerkProvider>
      <html lang="en"  className="dark h-full w-full overflow-hidden  ">
        <body
          className={`${geistSans.variable} ${geistMono.variable}  antialiased h-full w-full m-0 p-0`}
        >
          <SignedOut>
            <SignInButton />
            <SignUpButton />
          </SignedOut>
          <SignedIn>
          <div className="fixed top-4 left-4">
         
          </div>
          {children}
          </SignedIn>
         
        </body>
      </html>
    </ClerkProvider>
=======
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
>>>>>>> parent of 1934c92 (added clerk authentication basic layout setup)
  );
}
